name: vault
description: "app to store files encrypted"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
