name: vault
description: "app to store files encrypted"
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.6
  dartx: ^1.2.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
