name: CICD
run-name: Create Release On Push
on:
  push:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    name: CICD
    steps:
      - uses: laguna-studios/fhs@1.0.8
        with:
          keystore_base64: ${{ secrets.KEYSTORE }}
          key_properties: ${{ secrets.KEY_PROPERTIES }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          qa: false
          create_release: true
          publish: false
          flutter_version: "3.24.5"
